const key = "bc48805e97399455fe635190dcfad141";
const requests = {
  Originals: `/discover/tv?api_key=${key}&with_networks=213`,
  latest: `/movie/latest?api_key=${key}&language=en-US`,
  popular: `/movie/popular?api_key=${key}&language=en-US&page=1`,
  top_rated: `/movie/top_rated?api_key=${key}&language=en-US&page=1`,
  upcomming: `/movie/upcoming?api_key=${key}&language=en-US&page=1`,
  Action: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=28`,
  Adventure: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=12`,
  Comedy: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=35`,
  Animation: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=16`,
  Crime: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=80`,
  Documentary: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=99`,
  Drama: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=18`,
  Family: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=10751`,
  Fantasy: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=14`,
  History: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=36`,
  Horror: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=27`,
  Music: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=10402`,
  Mystery: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=9648`,
  Romance: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=10749`,
  Science_Fiction: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=878`,
  TV_Movie: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=10770`,
  Thriller: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=53`,
  War: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=10752`,
  Western: `/discover/movie?api_key=${key}&language=en-US&page=1&with_genres=37`,
};
export default requests;
